# Site settings
title: Steve Kehlet
email: steve.kehlet@gmail.com
description: >
  Personal website for Steve Kehlet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevekehlet.com" # the base hostname & protocol for your site
twitter_username: skehlet
github_username:  skehlet

# Build settings
markdown: kramdown
